# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commentform.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTreeWidgetItem, QMessageBox

from parse_comment import CommentBot

bot = CommentBot()
groups = []
students = []
subjects = []
for_send = {
    "group": 0,
    "stud": 0,
    "spec": 0
}


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, username, password):
        self.username = username
        self.password = password

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.group_list = QtWidgets.QListWidget(self.centralwidget)
        self.group_list.setGeometry(QtCore.QRect(10, 80, 91, 271))
        self.group_list.setObjectName("group_list")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.student_list = QtWidgets.QListWidget(self.centralwidget)
        self.student_list.setGeometry(QtCore.QRect(160, 80, 301, 271))
        self.student_list.setObjectName("student_list")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 20, 465, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.subject_list = QtWidgets.QListWidget(self.centralwidget)
        self.subject_list.setGeometry(QtCore.QRect(520, 80, 465, 111))
        self.subject_list.setObjectName("subject_list")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 190, 465, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 390, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 450, 31, 21))
        self.label_6.setObjectName("label_6")
        self.student_name_field = QtWidgets.QLineEdit(self.centralwidget)
        self.student_name_field.setGeometry(QtCore.QRect(40, 450, 101, 20))
        self.student_name_field.setObjectName("student_name_field")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 370, 1000, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(150, 380, 16, 321))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 480, 41, 21))
        self.label_7.setObjectName("label_7")
        self.group_label_info = QtWidgets.QLabel(self.centralwidget)
        self.group_label_info.setGeometry(QtCore.QRect(60, 480, 81, 21))
        self.group_label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.group_label_info.setObjectName("group_label_info")
        self.subject_label_info = QtWidgets.QLabel(self.centralwidget)
        self.subject_label_info.setGeometry(QtCore.QRect(10, 530, 131, 31))
        self.subject_label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_label_info.setObjectName("subject_label_info")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 510, 51, 21))
        self.label_10.setObjectName("label_10")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 570, 141, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gen_comment = QtWidgets.QPushButton(self.centralwidget)
        self.gen_comment.setGeometry(QtCore.QRect(20, 600, 121, 41))
        self.gen_comment.setStyleSheet("background-color:rgb(200, 200, 200);\n")
        self.gen_comment.setObjectName("gen_comment")
        self.send_comment = QtWidgets.QPushButton(self.centralwidget)
        self.send_comment.setGeometry(QtCore.QRect(20, 650, 121, 41))
        self.send_comment.setStyleSheet("background-color:rgb(255, 69, 72);")
        self.send_comment.setObjectName("send_comment")
        self.text_comment = QtWidgets.QTextEdit(self.centralwidget)
        self.text_comment.setGeometry(QtCore.QRect(180, 440, 361, 231))
        self.text_comment.setObjectName("text_comment")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(440, 390, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(750, 680, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(9)
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(950, 10, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(560, 480, 332, 170))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.irresponsible = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.irresponsible.setObjectName("irresponsible")
        self.gridLayout.addWidget(self.irresponsible, 5, 0, 1, 1)
        self.curious = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.curious.setObjectName("curious")
        self.gridLayout.addWidget(self.curious, 3, 0, 1, 1)
        self.good_theme = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.good_theme.setObjectName("good_theme")
        self.gridLayout.addWidget(self.good_theme, 2, 0, 1, 1)
        self.responsible = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.responsible.setObjectName("responsible")
        self.gridLayout.addWidget(self.responsible, 1, 0, 1, 1)
        self.bad_hw = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bad_hw.setObjectName("bad_hw")
        self.gridLayout.addWidget(self.bad_hw, 4, 0, 1, 1)
        self.smart = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.smart.setObjectName("smart")
        self.gridLayout.addWidget(self.smart, 2, 2, 1, 1)
        self.active = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.active.setObjectName("active")
        self.gridLayout.addWidget(self.active, 1, 2, 1, 1)
        self.bad_action = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bad_action.setObjectName("bad_action")
        self.gridLayout.addWidget(self.bad_action, 3, 2, 1, 1)
        self.creative = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.creative.setObjectName("creative")
        self.gridLayout.addWidget(self.creative, 5, 2, 1, 1)
        self.good_hw = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.good_hw.setObjectName("good_hw")
        self.gridLayout.addWidget(self.good_hw, 4, 2, 1, 1)
        self.good_action = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.good_action.setObjectName("good_action")
        self.gridLayout.addWidget(self.good_action, 6, 0, 1, 1)
        self.hardworker = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.hardworker.setObjectName("hardworker")
        self.gridLayout.addWidget(self.hardworker, 6, 2, 1, 1)
        self.distracted = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.distracted.setObjectName("distracted")
        self.gridLayout.addWidget(self.distracted, 7, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(520, 230, 465, 121))
        self.treeWidget.setObjectName("treeWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.set_groups()
        self.group_list.itemSelectionChanged.connect(self.group_changed)
        self.student_list.itemSelectionChanged.connect(self.student_changed)
        self.subject_list.itemSelectionChanged.connect(self.subject_changed)
        self.gen_comment.clicked.connect(self.generate_comment)
        self.send_comment.clicked.connect(self.send)
        self.text_comment.setReadOnly(True)

        self.responsible.stateChanged.connect(
            lambda state=self.responsible.isChecked(), which='responsible': self.changeCheckBoxState(state, which))

        self.irresponsible.stateChanged.connect(
            lambda state=self.irresponsible.isChecked(), which='irresponsible': self.changeCheckBoxState(state, which))

        self.bad_action.stateChanged.connect(
            lambda state=self.bad_action.isChecked(), which='bad_action': self.changeCheckBoxState(state, which))

        self.good_action.stateChanged.connect(
            lambda state=self.good_action.isChecked(), which='good_action': self.changeCheckBoxState(state, which))

        self.bad_hw.stateChanged.connect(
            lambda state=self.bad_hw.isChecked(), which='bad_hw': self.changeCheckBoxState(state, which))

        self.good_hw.stateChanged.connect(
            lambda state=self.good_hw.isChecked(), which='good_hw': self.changeCheckBoxState(state, which))

        self.active.stateChanged.connect(
            lambda state=self.active.isChecked(), which='active': self.changeCheckBoxState(state, which))

        self.distracted.stateChanged.connect(
            lambda state=self.distracted.isChecked(), which='distracted': self.changeCheckBoxState(state, which))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Logbook comments"))
        self.label.setText(_translate("MainWindow",
        "<html><head/><body><p align=\"center\">Доступные</p><p align=\"center\">Группы</p></body></html>"))
        self.label_2.setText(
        _translate("MainWindow", "<html><head/><body><p align=\"center\">Выберите студента</p></body></html>"))
        self.label_3.setText(
        _translate("MainWindow", "<html><head/><body><p align=\"center\">Выберите предмет</p></body></html>"))
        self.label_4.setText(
        _translate("MainWindow", "<html><head/><body><p align=\"center\">Существующие отзывы</p></body></html>"))
        self.label_5.setText(_translate("MainWindow",
        "<html><head/><body><p align=\"center\">Блок </p><p align=\"center\">Информации</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Имя:"))
        self.label_7.setText(_translate("MainWindow", "Группа:"))
        self.group_label_info.setText(_translate("MainWindow", "???????"))
        self.subject_label_info.setText(_translate("MainWindow", "???????"))
        self.label_10.setText(_translate("MainWindow", "Предмет:"))
        self.gen_comment.setText(_translate("MainWindow", "Сгенерировать отзыв"))
        self.send_comment.setText(_translate("MainWindow", "Отправить отзыв"))
        self.label_11.setText(_translate("MainWindow", "Создать отзыв"))
        self.label_12.setText(_translate("MainWindow", "Developed by GendalfBlack, Glitch33r"))
        self.label_13.setText(_translate("MainWindow", "v1.1.1"))
        self.irresponsible.setText(_translate("MainWindow", "Безответственный"))
        self.curious.setText(_translate("MainWindow", "Любопытный"))
        self.good_theme.setText(_translate("MainWindow", "Отлично\nразобрался в теме"))
        self.responsible.setText(_translate("MainWindow", "Отвественный"))
        self.bad_hw.setText(_translate("MainWindow", "Не выполняет дз"))
        self.smart.setText(_translate("MainWindow", "Умный"))
        self.active.setText(_translate("MainWindow", "Активный"))
        self.bad_action.setText(_translate("MainWindow", "Полохое поведение"))
        self.creative.setText(_translate("MainWindow", "Креативный"))
        self.good_hw.setText(_translate("MainWindow", "Положительное дз"))
        self.good_action.setText(_translate("MainWindow", "Положительное поведение"))
        self.hardworker.setText(_translate("MainWindow", "Трудолюбивость"))
        self.distracted.setText(_translate("MainWindow", "Отвлекается"))
        self.treeWidget.headerItem().setHidden(True)

    def changeCheckBoxState(self, toggle, which):
        if toggle == QtCore.Qt.Checked:
            if which == "responsible":
                self.irresponsible.setEnabled(False)
            if which == "irresponsible":
                self.responsible.setEnabled(False)
            if which == "bad_action":
                self.good_action.setEnabled(False)
            if which == "good_action":
                self.bad_action.setEnabled(False)
            if which == "good_hw":
                self.bad_hw.setEnabled(False)
            if which == "bad_hw":
                self.good_hw.setEnabled(False)
            if which == "active":
                self.distracted.setEnabled(False)
            if which == "distracted":
                self.active.setEnabled(False)
        elif toggle == QtCore.Qt.Unchecked:
            if which == "responsible":
                self.irresponsible.setEnabled(True)
            if which == "irresponsible":
                self.responsible.setEnabled(True)
            if which == "bad_action":
                self.good_action.setEnabled(True)
            if which == "good_action":
                self.bad_action.setEnabled(True)
            if which == "good_hw":
                self.bad_hw.setEnabled(True)
            if which == "bad_hw":
                self.good_hw.setEnabled(True)
            if which == "active":
                self.distracted.setEnabled(True)
            if which == "distracted":
                self.active.setEnabled(True)

    def generate_comment(self):
        self.text_comment.clear()
        comment = ''
        if self.responsible.isChecked():
            comment += random.choice(
                ["Прекрасно проявил себя на занятиях",
                 "Отлично проявляет себя на занятиях",
                 "Замечательно проявил себя в данном блоке",
                 "Ответственно отнесся к блоку",
                 "Проявил себя как ответственный студент"]
            ) + ". "
        if self.active.isChecked():
            comment += random.choice(
                ["Проявляет себя заинтересованным и всегда вовлечен в работу",
                 "Берет участие в любой активности, отвечая на вопросы и предоставляя хорошие идеи",
                 "Быстро справляется с любыми заданиями на отлично!"]
            ) + ". "
        if self.good_theme.isChecked():
            comment += random.choice(
                ["Усвоение материала не вызвало никаких проблем",
                 "С легкостью разобрался со всем материалом блока",
                 "Студент с легкостью смог разобраться в теме и может использовать полученные знания самостоятельно"]
            ) + ". "
        if self.smart.isChecked():
            comment += random.choice(
                ["Студент самостоятельно может применять знания и использовать их в нестандартных ситуациях",
                 "Может самостоятельно работать над более сложными проектами",
                 "Является одним из лучших в группе!",
                 'В числе первых справляется с заданиями, всегда выполняя работу на "отлично"',
                 "Является примером для всей группы"]
            ) + ". "
        if self.curious.isChecked():
            comment += random.choice(
                ["У студента крайне пытливый ум, что помогает ему справляться с любыми заданиями",
                 "Всегда задает интересные вопросы",
                 "Всегда заинтересован в дополнительных знаниях по теме"]
            ) + ". "
        if self.bad_action.isChecked():
            comment += random.choice(
                ["Поведение оставляет желать лучшего",
                 "Стоит больше внимания уделить поведению"]
            ) + ". "
        if self.bad_hw.isChecked():
            comment += random.choice(
                ["К сожалению, следует больше внимания уделить домашним заданиям",
                 "Больше внимания к домашним заданиям, т.к. с ними есть проблемы",
                 "Следует больше внимания уделять домашним заданиям"]
            ) + ". "
        if self.good_hw.isChecked():
            comment += random.choice(
                ["Всегда сдает домашние задания на отлично",
                 "Домашние задания всегда верны и сданы вовремя",
                 "Работа над домашними заданиями вызывает только восторг",
                 "Домашние задания всегда выполнены на высшем уровне"]
            ) + ". "
        if self.irresponsible.isChecked():
            comment += random.choice(
                ["К изучению темы подошел спустя рукава. Работы сделаны очень поверхностно",
                 "К сожалению, работа на парах не воспринимается должным образом",
                 "Плохо работает на парах, что ведет к соответствующим оценкам"]
            ) + ". "
        if self.creative.isChecked():
            comment += random.choice(
                ["Предоставлял оригинальные работы, подходя к каждой теме максимально креативно",
                 "Оригинально подходит к заданиям", "Всегда находит оригинальные решения",
                 "Выделяется нестандартными работами на фоне группы",
                 "Часто выделяется из группы нестандартным подходом",
                 "Креативно выполняет все работы, о чем могут сказать отличные оценки"]
            ) + ". "
        if self.good_action.isChecked():
            comment += random.choice(
                ["Является примером поведения для всей группы",
                 "Поведение на парах претензий не вызывает :)",
                 "Поведение на парах всегда отличное"]
            ) + ". "
        if self.hardworker.isChecked():
            comment += random.choice(
                ["Усердно работал над каждой темой",
                 "Каждая из работ стоит отдельного внимания",
                 "Каждая из работ студента выполнена идеально",
                 "Работа на парах всегда на высоте",
                 "На каждом уроке выкладывался на полную",
                 "Провел достойную работу над каждым из своих проектов"]
            ) + ". "
        if self.distracted.isChecked():
            comment += random.choice(
                ["Часто переключает внимание на посторонние темы и не может включиться в работу",
                 "Задает интересные вопросы, однако не всегда по теме",
                 "Может отвлекаться на посторонние разговоры или другую деятельность"]
            ) + ". "

        if comment == '':
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setWindowTitle("Comment generation")
            msg.setText("Вы не выбрали ни одного критерия. Генерация невозможна :(")
            msg.exec_()
        else:
            self.text_comment.setReadOnly(False)

        self.text_comment.setText(comment)

    def send(self):
        bot.login(self.username, self.password)
        if all(v != 0 for v in for_send.values()) and self.text_comment.toPlainText() != '':
            result = bot.send_comment(
                str(for_send['group']),
                str(for_send['stud']),
                for_send['spec'],
                self.text_comment.toPlainText()
            )
            if result:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setWindowTitle("Comment sending")
                msg.setText(
                    "Комментарий успешно добавлен!\nПри желании можете сделать проверку в Logbook!\n"
                    "\nСпасибо за использовние нашей разработки!"
                )
                msg.exec_()
            else:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setWindowTitle("Comment sending")
                msg.setText(
                    "Упс.. Что-то пошло не так :(\nПроверьте все данные и попробуйте еще раз, или попробуйте позже."
                )
                msg.exec_()
        else:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setWindowTitle("Comment sending")
            msg.setText(
                "Вы не выбрали один из елементов: группа, студент, предмет или комментарий.\nОтправка невозможна :("
            )
            msg.exec_()

    def set_groups(self):
        bot.login(self.username, self.password)
        for i in bot.get_groups():
            groups.append(i)
            self.group_list.addItem(i['name'])

    def group_changed(self):
        current_item = self.group_list.currentItem().text()
        self.group_label_info.setText(current_item)
        for item in groups:
            if item['name'] == current_item:
                idx = item['id']

        for_send['group'] = str(idx)
        self.set_students(idx)

    def set_students(self, id):
        self.student_list.clear()
        students.clear()
        bot.login(self.username, self.password)
        for i in bot.get_students_of_group(id):
            students.append(i)
            self.student_list.addItem(i['name'])

    def student_changed(self):
        current_item = self.student_list.currentItem().text()
        self.student_name_field.setText(current_item.split(' ')[1])
        for item in students:
            if item['name'] == current_item:
                idx = item['id']

        for_send['stud'] = str(idx)
        self.set_subjects(idx)
        self.set_comments(idx)

    def set_subjects(self, id):
        self.subject_list.clear()
        subjects.clear()
        bot.login(self.username, self.password)
        for i in bot.get_subjects_for_group(id):
            subjects.append(i)
            self.subject_list.addItem(i['name'])

    def set_comments(self, id):
        self.treeWidget.clear()
        bot.login(self.username, self.password)
        for idx, i in enumerate(bot.get_student_comments(id)):
            topItem = QTreeWidgetItem(self.treeWidget)
            topItem.setText(idx, i['teacher'])
            subject = QTreeWidgetItem(topItem)
            subject.setText(0, f"Предмет: {i['subject']}")
            comment = QTreeWidgetItem(topItem)
            comment.setText(0, "\n".join(i["comment"].split(".")))

    def subject_changed(self):
        current_item = self.subject_list.currentItem().text()
        self.subject_label_info.setText("\n".join(current_item.split(" ")))
        for item in subjects:
            if item['name'] == current_item:
                idx = item['id']

        for_send['spec'] = int(idx)
