from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow:
    def setupUi(self, MainWindow, username, password):
        self.username = username
        self.password = password

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 840)
        MainWindow.setMinimumSize(QtCore.QSize(980, 840))
        MainWindow.setMaximumSize(QtCore.QSize(980, 840))
        font_default = QtGui.QFont()
        font_default.setFamily("Comic Sans MS")
        font_default.setPointSize(9)

        font_bold = QtGui.QFont()
        font_bold.setFamily("Comic Sans MS")
        font_bold.setPointSize(10)
        font_bold.setBold(True)
        font_bold.setWeight(75)

        MainWindow.setFont(font_default)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.group_list = QtWidgets.QListWidget(self.centralwidget)
        self.group_list.setGeometry(QtCore.QRect(20, 60, 101, 291))
        self.group_list.setFont(font_default)
        self.group_list.setObjectName("group_list")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 101, 51))
        self.label.setFont(font_bold)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.student_list = QtWidgets.QListWidget(self.centralwidget)
        self.student_list.setGeometry(QtCore.QRect(190, 50, 301, 301))
        self.student_list.setFont(font_default)
        self.student_list.setObjectName("student_list")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 0, 301, 41))
        self.label_2.setFont(font_bold)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 0, 391, 41))
        self.label_3.setFont(font_bold)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.subject_list = QtWidgets.QListWidget(self.centralwidget)
        self.subject_list.setGeometry(QtCore.QRect(560, 50, 391, 111))
        self.subject_list.setFont(font_default)
        self.subject_list.setObjectName("subject_list")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 170, 391, 31))
        self.label_4.setFont(font_bold)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 380, 151, 41))
        self.label_5.setFont(font_bold)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 440, 31, 21))
        self.label_6.setObjectName("label_6")
        self.student_name_field = QtWidgets.QLineEdit(self.centralwidget)
        self.student_name_field.setGeometry(QtCore.QRect(40, 440, 101, 20))
        self.student_name_field.setObjectName("student_name_field")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 370, 981, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(140, 380, 20, 431))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 500, 41, 21))
        self.label_7.setObjectName("label_7")
        self.group_label_info = QtWidgets.QLabel(self.centralwidget)
        self.group_label_info.setGeometry(QtCore.QRect(60, 500, 81, 21))
        self.group_label_info.setText("")
        self.group_label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.group_label_info.setObjectName("group_label_info")
        self.subject_label_info = QtWidgets.QLabel(self.centralwidget)
        self.subject_label_info.setGeometry(QtCore.QRect(10, 580, 131, 71))
        self.subject_label_info.setText("")
        self.subject_label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_label_info.setObjectName("subject_label_info")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 560, 121, 21))
        self.label_10.setObjectName("label_10")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 650, 151, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gen_comment = QtWidgets.QPushButton(self.centralwidget)
        self.gen_comment.setGeometry(QtCore.QRect(10, 670, 121, 51))
        self.gen_comment.setFont(font_default)
        self.gen_comment.setStyleSheet("background-color:#6c757d;\ncolor: #ffffff;")
        self.gen_comment.setObjectName("gen_comment")
        self.send_comment = QtWidgets.QPushButton(self.centralwidget)
        self.send_comment.setGeometry(QtCore.QRect(10, 740, 121, 51))
        self.send_comment.setFont(font_default)
        self.send_comment.setStyleSheet("background-color: #28a745;\ncolor: #ffffff;")
        self.send_comment.setObjectName("send_comment")
        self.text_comment = QtWidgets.QTextEdit(self.centralwidget)
        self.text_comment.setGeometry(QtCore.QRect(560, 540, 401, 241))
        self.text_comment.setObjectName("text_comment")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(400, 380, 311, 41))
        self.label_11.setFont(font_bold)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 800, 291, 41))
        self.label_12.setFont(font_bold)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(910, 805, 71, 31))
        self.label_13.setFont(font_bold)
        self.label_13.setObjectName("label_13")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(180, 540, 341, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.irresponsible = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.irresponsible.setObjectName("irresponsible")
        self.gridLayout.addWidget(self.irresponsible, 5, 0, 1, 1)
        self.curious = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.curious.setObjectName("curious")
        self.gridLayout.addWidget(self.curious, 3, 0, 1, 1)
        self.good_theme = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.good_theme.setObjectName("good_theme")
        self.gridLayout.addWidget(self.good_theme, 2, 0, 1, 1)
        self.responsible = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.responsible.setObjectName("responsible")
        self.gridLayout.addWidget(self.responsible, 1, 0, 1, 1)
        self.bad_hw = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bad_hw.setObjectName("bad_hw")
        self.gridLayout.addWidget(self.bad_hw, 4, 0, 1, 1)
        self.smart = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.smart.setObjectName("smart")
        self.gridLayout.addWidget(self.smart, 2, 2, 1, 1)
        self.active = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.active.setObjectName("active")
        self.gridLayout.addWidget(self.active, 1, 2, 1, 1)
        self.bad_action = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bad_action.setObjectName("bad_action")
        self.gridLayout.addWidget(self.bad_action, 3, 2, 1, 1)
        self.creative = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.creative.setObjectName("creative")
        self.gridLayout.addWidget(self.creative, 5, 2, 1, 1)
        self.good_hw = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.good_hw.setObjectName("good_hw")
        self.gridLayout.addWidget(self.good_hw, 4, 2, 1, 1)
        self.good_action = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.good_action.setObjectName("good_action")
        self.gridLayout.addWidget(self.good_action, 6, 0, 1, 1)
        self.hardworker = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.hardworker.setObjectName("hardworker")
        self.gridLayout.addWidget(self.hardworker, 6, 2, 1, 1)
        self.distracted = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.distracted.setObjectName("distracted")
        self.gridLayout.addWidget(self.distracted, 7, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(560, 210, 391, 141))
        self.treeWidget.setFont(font_default)
        self.treeWidget.setObjectName("treeWidget")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 800, 981, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.add_phrase = QtWidgets.QPushButton(self.centralwidget)
        self.add_phrase.setGeometry(QtCore.QRect(840, 440, 111, 51))
        self.add_phrase.setFont(font_default)
        self.add_phrase.setStyleSheet("background-color:#6c757d;\ncolor: #ffffff;")
        self.add_phrase.setObjectName("add_phrase")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 440, 160, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ua_lang = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ua_lang.setObjectName("ua_lang")
        self.verticalLayout.addWidget(self.ua_lang)
        self.ru_lang = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ru_lang.setObjectName("ru_lang")
        self.ru_lang.setChecked(True)
        self.verticalLayout.addWidget(self.ru_lang)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(370, 440, 151, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.own_phrases = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.own_phrases.setObjectName("own_phrases")
        self.verticalLayout_2.addWidget(self.own_phrases)
        self.all_phrases = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.all_phrases.setObjectName("all_phrases")
        self.all_phrases.setChecked(True)
        self.verticalLayout_2.addWidget(self.all_phrases)
        MainWindow.setCentralWidget(self.centralwidget)
        self.treeWidget.headerItem().setHidden(True)
        self.text_comment.setReadOnly(True)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("Logbook comments")
        self.label.setText("Доступные\nГруппы")
        self.label_2.setText("Выберите студента")
        self.label_3.setText("Выберите предмет")
        self.label_4.setText("Существующие отзывы")
        self.label_5.setText("Блок информации")
        self.label_6.setText("Имя:")
        self.label_7.setText("Группа:")
        self.label_10.setText("Предмет:")
        self.gen_comment.setText("Сгенерировать\nотзыв")
        self.send_comment.setText("Отправить отзыв")
        self.label_11.setText("Создать отзыв")
        self.label_12.setText("Developed by GendalfBlack, Glitch33r")
        self.label_13.setText("v1.3.0")
        self.irresponsible.setText("Безответственный")
        self.curious.setText("Любознательный")
        self.good_theme.setText("Отлично\nразобрался в теме")
        self.responsible.setText("Отвественный")
        self.bad_hw.setText("Не выполняет дз")
        self.smart.setText("Умный")
        self.active.setText("Активный")
        self.bad_action.setText("Полохое поведение")
        self.creative.setText("Креативный")
        self.good_hw.setText("Положительное дз")
        self.good_action.setText("Положительное поведение")
        self.hardworker.setText("Трудолюбивость")
        self.distracted.setText("Отвлекается")
        self.treeWidget.headerItem().setText(0, "")
        self.add_phrase.setText("Добавить свою\nфразу")
        self.ua_lang.setText("Украинский")
        self.ru_lang.setText("Русский")
        self.own_phrases.setText("Свои фразы")
        self.all_phrases.setText("Все фразы")
